version: '3.5'

services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    networks:
      - backend
    ports:
      - '8000:8000'

networks:
  backend:
    name: life-efficiency

volumes:
  dynamodata: {}
