version: '3.5'

services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    networks:
      - backend
    ports:
      - '8000:8000'
    command: "-jar DynamoDBLocal.jar -sharedDb"
  app-node:
    depends_on:
      - dynamo
    image: amazon/aws-cli
    container_name: app-node
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    ports:
      - "8080:8080"
    networks:
      - backend
    entrypoint:
      - /bin/sh
    command:
      - -c
      - >-
        aws dynamodb create-table --endpoint-url http://dynamodb:8000 --region eu-west-1 --table-name life-efficiency_local_shopping-list --key-schema AttributeName=Id,KeyType=HASH --attribute-definitions AttributeName=Id,AttributeType=S --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD;
        aws dynamodb create-table --endpoint-url http://dynamodb:8000 --region eu-west-1 --table-name life-efficiency_local_repeating-items --key-schema AttributeName=Id,KeyType=HASH --attribute-definitions AttributeName=Id,AttributeType=S --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD;
        aws dynamodb create-table --endpoint-url http://dynamodb:8000 --region eu-west-1 --table-name life-efficiency_local_shopping-history --key-schema AttributeName=Id,KeyType=HASH --attribute-definitions AttributeName=Id,AttributeType=S --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD;
        aws dynamodb create-table --endpoint-url http://dynamodb:8000 --region eu-west-1 --table-name life-efficiency_local_goals --key-schema AttributeName=Id,KeyType=HASH --attribute-definitions AttributeName=Id,AttributeType=S --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD;
        aws dynamodb create-table --endpoint-url http://dynamodb:8000 --region eu-west-1 --table-name life-efficiency_local_weekly-todos --key-schema AttributeName=Id,KeyType=HASH --attribute-definitions AttributeName=Id,AttributeType=S --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD;
        aws dynamodb create-table --endpoint-url http://dynamodb:8000 --region eu-west-1 --table-name life-efficiency_local_todo-list --key-schema AttributeName=Id,KeyType=HASH --attribute-definitions AttributeName=Id,AttributeType=N --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD


networks:
  backend:
    name: life-efficiency

volumes:
  dynamodata: {}
