AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Life efficiency endpoints!"
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 15
        Runtime: python3.8
        Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
        Environment:
            Variables:
                # Powertools env vars: https://awslabs.github.io/aws-lambda-powertools-python/#environment-variables
                LOG_LEVEL: INFO
                POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
                POWERTOOLS_LOGGER_LOG_EVENT: true
                POWERTOOLS_METRICS_NAMESPACE: MyServerlessApplication
                POWERTOOLS_SERVICE_NAME: hello
                SPREADSHEET_KEY: "12vPGwr5Ds3ZygiHf0-XXVXuOZFhH7VTLrWioUroeUbA"

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: shopping.shopping_lambda_handlers.shopping_handler
            CodeUri: life-efficiency
            Description: Hello World function
            Policies:
              - S3ReadPolicy:
                  BucketName: "life-efficiency"
            Events:
                CatchAll:
                    Type: Api
                    Properties:
                        Path: /shopping/{subcommand+}
                        Method: any
            Tags:
                PARENT_COMMAND: SHOPPING
                COMMAND: HISTORY

Outputs:
    HelloWorldApigwURL:
      Description: "API Gateway endpoint URL for Prod environment for Hello World Function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn
