AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Life efficiency endpoints!"
Globals:
    Function:
        Timeout: 30
        Runtime: python3.9
        Tracing: Active
        Environment:
            Variables:
                LOG_LEVEL: INFO
                POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
                POWERTOOLS_LOGGER_LOG_EVENT: true
                POWERTOOLS_METRICS_NAMESPACE: MyServerlessApplication
                POWERTOOLS_SERVICE_NAME: hello
                SPREADSHEET_KEY_SECRET_NAME: !Sub "life-efficiency/${Environment}/spreadsheet-key"

Parameters:
    Environment:
        Type: String
        Default: Dev
        AllowedValues:
            - Dev
            - Prod

Resources:
    SpreadsheetKeySecret:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: !Sub "life-efficiency/${Environment}/spreadsheet-key"
    ShoppingFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: configuration.handler
            CodeUri: life-efficiency
            Description: Hello World function
            Policies:
              - S3ReadPolicy:
                  BucketName: "life-efficiency"
              - AWSSecretsManagerGetSecretValuePolicy:
                  SecretArn: !Ref SpreadsheetKeySecret
            Events:
                CatchAll:
                    Type: Api
                    Properties:
                        Path: /{command}/{subcommand+}
                        Method: any
                        RestApiId: !Ref Api
    Api:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref Environment
