AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Life efficiency endpoints!"
Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
        POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_METRICS_NAMESPACE: MyServerlessApplication
        POWERTOOLS_SERVICE_NAME: hello
Mappings:
  EnvironmentMap:
    Dev:
      Lower: dev
    Prod:
      Lower: prod
Parameters:
  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - "leon-patmore-life-efficiency-${LowerEnvironment}"
        - LowerEnvironment: !FindInMap [EnvironmentMap, !Ref Environment, "Lower"]
  ShoppingListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_shopping-list"
  RepeatingItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_repeating-items"
  ShoppingHistoryTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_shopping-history"
  GoalsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_goals"
  WeeklyTodosTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_weekly-todos"
  TodoListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_todo-list"
  TodoSetTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_todo-sets"
  FinanceBalanceInstances:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_balance_instances"
  FinanceBalanceChanges:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_balance_changes"
  ShoppingItemIgnore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "life-efficiency_${Environment}_shopping_item_ignore"
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  LifeEfficiencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: configuration.handler
      CodeUri: life-efficiency
      Description: Function for life efficiency
      Environment:
        Variables:
          ENV: !Sub "${Environment}"
          S3_BUCKET_NAME: !Ref Bucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref Bucket
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_shopping-list"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_repeating-items"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_shopping-history"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_goals"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_weekly-todos"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_todo-list"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_todo-sets"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_balance_instances"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_balance_changes"
        - DynamoDBCrudPolicy:
            TableName: !Sub "life-efficiency_${Environment}_shopping_item_ignore"
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{command}/{subcommand+}
            Method: any
            RestApiId: !Ref Api
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
