version: 2.1

orbs:
  python: circleci/python@0.2.1
  sam: circleci/aws-sam-serverless@2.0.0

jobs:
  test_and_lint:
    executor: python/default
    steps:
      - checkout
      - run: pipenv install -d
      - run: pipenv run python -m flake8
      - run: export PYTHONPATH=./life-efficiency && pipenv run python -m pytest --cov=life-efficiency
  deploy_staging:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/build:
          template: template.yaml
      - sam/deploy:
          stack-name: life-efficiency-dev

workflows:
  main:
    jobs:
      - test_and_lint
      - deploy_staging
